FROM python:3.8-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY main.py .
COPY ../model/model.pkl /app/model.pkl
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]