FROM python:3.8-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
COPY model/model.pkl /app/model/model.pkl
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]

